//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRemains.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public int OrderID { get; set; }

        public Nullable<int> RestaurantID { get; set; }
        public Nullable<int> PostedFoodID { get; set; }

        [Required(ErrorMessage = "Quantity is required")]
        public Nullable<int> Quantity { get; set; }

        [Required(ErrorMessage = "First Name is required")]
        public string CustomerFirstName { get; set; }

        [Required(ErrorMessage = "Last Name is required")]
        public string CustomerLastName { get; set; }

        [Required(ErrorMessage = "Email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string EmailID { get; set; }

        [Required(ErrorMessage = "Contact No is required")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid contact number, (ex: 123-414-1010)")]
        public string ContactNo { get; set; }
        public string OrderReferenceNo { get; set; }
        public string FoodItem { get; set; }
        public string RestaurantName { get; set; }

        public virtual PostFoodMaster PostFoodMaster { get; set; }
        public virtual RestaurantMaster RestaurantMaster { get; set; }
    }
}
