//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodRemains.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RestaurantMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RestaurantMaster()
        {
            this.FeedbackMasters = new HashSet<FeedbackMaster>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PostFoodMasters = new HashSet<PostFoodMaster>();
        }
    
        public int RestaurantID { get; set; }

        [Required(ErrorMessage = "Restaurant Name is required")]
        public string RestaurantName { get; set; }

        [Required(ErrorMessage = "Location is required")]
        public string Location { get; set; }

        [Required(ErrorMessage = "Opening Hour is required")]
        public Nullable<System.TimeSpan> OpeningHour { get; set; }

        [Required(ErrorMessage = "Closing Hour is required")]
        public Nullable<System.TimeSpan> ClosingHour { get; set; }

        [Required(ErrorMessage = "Enter available services")]
        public string AvailableService { get; set; }

        [Required(ErrorMessage = "Cuisine is required")]
        public string Cuisine { get; set; }
        public string Photo { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public int? Quantity { get; set; }
        public string Website { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedbackMaster> FeedbackMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual OwnerMaster OwnerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostFoodMaster> PostFoodMasters { get; set; }
    }
}
